services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./fluentpdo/public:/var/www/html/fluentpdo/public
      - ./medoo/public:/var/www/html/medoo/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - php-fluentpdo
      - php-medoo
    networks:
      - app-network

  php-fluentpdo:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-fluentpdo
    container_name: php-fluentpdo
    volumes:
      - ./fluentpdo:/var/www/html/fluentpdo
    working_dir: /var/www/html/fluentpdo
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - app-network

  php-medoo:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-medoo
    container_name: php-medoo
    volumes:
      - ./medoo:/var/www/html/medoo
    working_dir: /var/www/html/medoo
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network

  app-seed-fluentpdo:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-fluentpdo
    container_name: app-seed-fluentpdo
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      php-fluentpdo:
        condition: service_started
    command: ["/var/www/html/docker/scripts/wait-for-it.sh", "-t", "60", "mysql:3306", "--", "php", "/var/www/html/docker/scripts/seed.php"]
    networks:
      - app-network
    restart: "no"

  app-seed-medoo:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-medoo
    container_name: app-seed-medoo
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      php-medoo:
        condition: service_started
    command: ["/var/www/html/docker/scripts/wait-for-it.sh", "-t", "60", "mysql:3306", "--", "php", "/var/www/html/docker/scripts/seed.php"]
    networks:
      - app-network
    restart: "no"

networks:
  app-network:
    driver: bridge