services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fluentpdo
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network

  app-seed:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app-seed
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy 
      php:
        condition: service_started 
    command: ["/var/www/html/docker/scripts/wait-for-it.sh", "mysql:3306", "--", "php", "/var/www/html/docker/scripts/seed.php"]
    networks:
      - app-network
    restart: "no"

networks:
  app-network:
    driver: bridge